"""Authentication: who is calling, and with which permissions.

Two token shapes reach this server from Microsoft Entra ID:

* Delegated (a person signed in to Claude or VS Code): permissions in ``scp``.
* App-only (a Foundry agent identity): permissions in ``roles``.

``EntraJWTVerifier`` validates either one and merges both claims into a single
permission set, so every tool can declare one requirement such as
``require_scopes("dms.read")`` and have it work for people and agents alike.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from fastmcp.server.auth import RemoteAuthProvider
from fastmcp.server.auth.providers.jwt import JWTVerifier
from fastmcp.server.dependencies import get_access_token

from server.config import Settings

READ = "dms.read"
WRITE = "dms.write"
MANAGER = "dms.manager"
ALL_PERMISSIONS = (READ, WRITE, MANAGER)


class EntraJWTVerifier(JWTVerifier):
    """JWT verifier that treats Entra app roles as permissions too.

    Only permissions this server defines are kept. An unexpected value in a
    token (for example a role from another app) can never widen access.
    """

    def _extract_scopes(self, claims: dict[str, Any]) -> list[str]:
        scopes = set(super()._extract_scopes(claims))
        roles = claims.get("roles") or []
        if isinstance(roles, str):
            roles = [roles]
        scopes.update(roles)
        return sorted(s for s in scopes if s in ALL_PERMISSIONS)


def build_auth(settings: Settings) -> RemoteAuthProvider:
    """Resource-server auth: verify tokens, publish Protected Resource Metadata."""
    if settings.auth_mode == "entra":
        tenant = settings.entra_tenant_id
        issuer = f"https://login.microsoftonline.com/{tenant}/v2.0"
        verifier = EntraJWTVerifier(
            jwks_uri=f"https://login.microsoftonline.com/{tenant}/discovery/v2.0/keys",
            issuer=issuer,
            # v2 access tokens carry the API's client ID as the audience.
            audience=settings.entra_client_id,
            algorithm="RS256",
        )
        client_id = settings.entra_client_id
        return RemoteAuthProvider(
            token_verifier=verifier,
            authorization_servers=[issuer],
            base_url=settings.public_base_url,
            resource_name="Dealer Sales Assistant",
            # Advertise only the baseline scope. Higher scopes are requested
            # through step-up when first needed (least privilege).
            scopes_supported=[f"api://{client_id}/{READ}"],
        )

    # Local mode: same verifier, keys generated by `uv run dev-token`.
    public_key = Path(settings.local_public_key_path).read_text()
    verifier = EntraJWTVerifier(
        public_key=public_key,
        issuer=settings.local_issuer,
        audience=settings.local_audience,
        algorithm="RS256",
    )
    return RemoteAuthProvider(
        token_verifier=verifier,
        authorization_servers=[settings.local_issuer],
        base_url=settings.public_base_url,
        resource_name="Dealer Sales Assistant (local)",
        scopes_supported=[READ],
    )


@dataclass(frozen=True)
class Caller:
    """The verified identity behind the current request."""

    id: str
    kind: str  # "user" or "app"
    name: str
    permissions: frozenset[str]

    @property
    def is_manager(self) -> bool:
        return MANAGER in self.permissions


def current_caller() -> Caller:
    """Identity from the verified token. Never from tool arguments."""
    token = get_access_token()
    if token is None:  # auth middleware guarantees this does not happen
        raise PermissionError("no authenticated caller")
    claims = token.claims or {}
    return Caller(
        id=str(claims.get("oid") or claims.get("sub")),
        kind="app" if claims.get("idtyp") == "app" else "user",
        name=str(claims.get("name") or claims.get("azp") or "unknown"),
        permissions=frozenset(token.scopes),
    )
